from flask import Flask, jsonify, request
from flask_cors import CORS
import json
import os
from datetime import datetime

app = Flask(name)
CORS(app)

DATA_FILE = "articles.json"

def load_articles():
if not os.path.exists(DATA_FILE):
with open(DATA_FILE, "w") as f:
json.dump([], f)

with open(DATA_FILE, "r") as f:
    articles = json.load(f)

if len(articles) == 0:
    default_article = {
        "title": "PulseGurgaon Launches",
        "summary": "Welcome to PulseGurgaon. This platform will soon automatically publish AI generated news.",
        "article": "PulseGurgaon has officially launched. Soon the system will automatically generate news articles using multiple AI providers.",
        "time": datetime.now().strftime("%Y-%m-%d"),
        "source": "PulseGurgaon"
    }

    articles.append(default_article)
    save_articles(articles)

return articles

def save_articles(data):
with open(DATA_FILE, "w") as f:
json.dump(data, f, indent=2)

@app.route("/")
def home():
return "PulseGurgaon backend running"

@app.route("/news")
def get_news():
articles = load_articles()
return jsonify(articles)

@app.route("/add", methods=["POST"])
def add_article():

data = request.json

article = {
    "title": data.get("title"),
    "summary": data.get("summary"),
    "article": data.get("article"),
    "time": datetime.now().strftime("%Y-%m-%d"),
    "source": "PulseGurgaon"
}

articles = load_articles()
articles.insert(0, article)

save_articles(articles)

return jsonify({"status": "added"})

@app.route("/generate")
def generate_ai_article():

# placeholder AI generator
title = "AI Generated Gurgaon Update"
summary = "This article was automatically generated by the PulseGurgaon AI system."
article = "PulseGurgaon is testing automated AI news generation. Soon articles will be created by multiple AI providers."

new_article = {
    "title": title,
    "summary": summary,
    "article": article,
    "time": datetime.now().strftime("%Y-%m-%d"),
    "source": "PulseGurgaon AI"
}

articles = load_articles()
articles.insert(0, new_article)

save_articles(articles)

return jsonify(new_article)

if name == "main":
app.run(host="0.0.0.0", port=10000)